# The following code is used to ensure that renv is activated when you
# start an R session for this project.

# If you're on a multi-user system, you might want to uncomment the
# following block, which helps handle permissions issues if multiple
# users share the same project folder.
# if (!interactive()) {
#   options(renv.consent = TRUE)
# }

# This file is automatically generated by renv. Do not edit it by hand.
if (Sys.getenv("R_PROFILE_USER") == "") {
  if (file.exists(".Renviron")) {
    readRenviron(".Renviron")
  }
  
  if (nzchar(Sys.getenv("RENV_PROFILE"))) {
    # Check for the existence of an renv profile-specific profile hook
    renv_profile_rprofile <- file.path("renv", "profiles", Sys.getenv("RENV_PROFILE"), "Rprofile.site")
    if (file.exists(renv_profile_rprofile)) {
      source(renv_profile_rprofile)
    }
  }

  if (file.exists("renv/activate.R")) {
    source("renv/activate.R")
  }
}
